export const languageTexts = {
    eng: {
        title_1: "Web Developer ",
        title_2: "Full Stack",
        text_1: "I am a FULL-STACK web application developer. I like working in FRONT-END because I understand very well the client/user requirements to achieve a good user experience.",
        text_2_part_1: "Likewise, I can work in any area. As seen in the section",
        text_link_1: "projects",
        text_2_part_2: ", I have two fully functional FULL-STACK developed applications.",
        text_3_part_1: "I am interested in continuing to improve my knowledge with the",
        text_link_2: "technologies",
        text_3_part_2: "that I usually use as good practices that every developer should have.",
        text_4_part_1: "I am currently studying Systems Engineering at the ",
        text_link_4: "Adventist University of Plata",
        text_4_part_2: ", studying the 4th year of the degree.",
        text_5: "Throughout my studies I worked on various projects that helped me choose what I like, but I am open to learning whatever is necessary in order to contribute.",
        degree_1: "Systems Analyst",
        degree_2: "Systems Engineer",
        skill_1: "English - Reading Comprehension",
        skill_2: "English - Verbal communication",
        skill_3: "Troubleshooting",
        skill_4: "Laborious",
        skill_5: "Creativity",
        skill_6: "Adaptability",
        skill_7: "Teamwork",

    },
    spa: {
        title_1: "Desarrollador Web ",
        title_2: "Full Stack",
        text_1: "Soy un desarrollador FULL-STACK de aplicaciones web. Me gusta trabajar en FRONT-END porque entiendo muy bien los requerimientos del cliente/usuario para lograr una buena experiencia de usuario.",
        text_2_part_1: "De igual manera, puedo trabajar en cualquier área. Como se ve en la sección de",
        text_link_1: "proyectos",
        text_2_part_2: ", cuento con dos aplicaciones desarrolladas FULL-STACK completamente funcionales.",
        text_3_part_1: "Estoy interesado en seguir mejorando mi conocimiento tanto con las",
        text_link_2: "tecnologías",
        text_3_part_2: "que suelo utilizar como en las buenas prácticas que debe tener todo desarrollador.",
        text_4_part_1: "Actualmente estoy estudiando Ingeniería en Sistemas en la ",
        text_link_4: "Universidad Adventista del Plata",
        text_4_part_2: ", cursando el 4to año de la carrera.",
        text_5: "A lo largo de mis estudios fui trabajando en diversos proyectos que me ayudaron a elegir lo que me gusta, pero estoy abierto a aprender lo que sea necesario con tal de contribuir.",
        degree_1: "Analista en Sistemas",
        degree_2: "Ingeniero en Sistemas",
        skill_1: "Inglés - Comprensión lectora",
        skill_2: "Inglés - Comunicación verbal",
        skill_3: "Resolución de Problemas",
        skill_4: "Laborioso",
        skill_5: "Creatividad",
        skill_6: "Adaptabilidad",
        skill_7: "Trabajo en Equipo",
    }
};