export const languageTexts = {
  eng: {
    title_1: "Web Developer ",
    title_2: "Full Stack",
    text_1: "I develop full-stack web applications. I care about building things that work well and feel right for the people using them — user experience is something I keep in mind from day one.",
    text_2_part_1: "I follow good practices and work well in team environments. In the",
    text_link_1: "projects ",
    text_2_part_2: "section you can see some of what I've built — complete, fully functional applications.",
    text_3_part_1: "I use AI as part of my workflow, it's just another tool and it helps me work more efficiently. I'm always looking to improve, both in the",
    text_link_2: "technologies",
    text_3_part_2: "I use and in the way I approach each problem.",
    text_4_part_1: "I'm finishing my Systems Engineering degree at the",
    text_link_4: "Universidad Adventista del Plata",
    text_4_part_2: ", currently in my final year.",
    degree_1: "Systems Analyst",
    degree_2: "Systems Engineer",
    skill_1: "English - Reading comprehension",
    skill_2: "English - Verbal communication",
    skill_4: "Teamwork",
    skill_5: "Time management",
    skill_6: "Attention to detail",
    skill_7: "Organization",
    skill_8: "Communication",
    contact_name: "Name",
    contact_email: "Email",
    contact_message: "Message",
    contact_send: "Send",
    contact_sending: "Sending...",
    contact_success: "Message sent! I'll get back to you soon.",
    contact_error: "Something went wrong. Try again.",
  },
  spa: {
    title_1: "Desarrollador Web ",
    title_2: "Full Stack",
    text_1: "Desarrollo aplicaciones web full-stack. Me importa que lo que construyo funcione bien y se sienta bien para quien lo usa — la experiencia del usuario es algo que tengo siempre en cuenta desde el primer momento.",
    text_2_part_1: "Trabajo con buenas prácticas y me manejo bien en equipos. En la sección de",
    text_link_1: "proyectos ",
    text_2_part_2: "podés ver algunas de las cosas que hice, aplicaciones completas y funcionales.",
    text_3_part_1: "Uso IA como parte de mi flujo de trabajo, para mí es una herramienta más y me ayuda a ser más eficiente y eficaz. Siempre estoy buscando mejorar, tanto en las",
    text_link_2: "tecnologías",
    text_3_part_2: "que uso como en la forma en que encaró cada problema.",
    text_4_part_1: "Estoy terminando Ingeniería en Sistemas en la",
    text_link_4: "Universidad Adventista del Plata",
    text_4_part_2: ", cursando el último año de la carrera.",
    degree_1: "Analista en Sistemas",
    degree_2: "Ingeniero en Sistemas",
    skill_1: "Inglés - Comprensión lectora",
    skill_2: "Inglés - Comunicación verbal",
    skill_4: "Trabajo en equipo",
    skill_5: "Gestión del tiempo",
    skill_6: "Atención al detalle",
    skill_7: "Organización",
    skill_8: "Comunicación",
    contact_name: "Nombre",
    contact_email: "Email",
    contact_message: "Mensaje",
    contact_send: "Enviar",
    contact_sending: "Enviando...",
    contact_success: "¡Mensaje enviado! Te respondo pronto.",
    contact_error: "Algo salió mal. Intentá de nuevo.",
  },
};